
services:
  myDataBase:
    image: postgres:15.3
    container_name: my-DB
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - StoreDeLaCruz:/var/lib/postgresql/data

volumes:
  StoreDeLaCruz: